

service: locusnine-service-dev
provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:*:*"

resources:
  Resources:
    LocusnineSaleDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'locusnineSaleDev'
    LocusnineRepsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'locusnineRepsDev'

functions:
  create:
    handler: handler.create
    events:
      -
        http:
          path: locusnine/create
          method: get
          cors: true
  getSaleData:
    handler: handler.getSaleData
    events:
      -
        http:
          path: locusnine/getSaleData
          method: get
          cors: true
  getReps:
    handler: handler.getReps
    events:
      -
        http:
          path: locusnine/getReps
          method: get
          cors: true
  getLeftPanelData:
    handler: handler.getLeftPanelData
    events:
      -
        http:
          path: locusnine/getLeftPanelData
          method: get
          cors: true